### ISSUE TITLE
Hide (or handle differently) Apps created secrets and apps

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-apps#12]
Right now we are creating the OAuth Apps and Bots by the HTTP APIv4. This will allow the sysadmin to go to the Apps or Bot listings and delete the secrets or apps. This will render the apps unusable. In order to avoid this, we should handle these bots and apps in a different way, so everything is centralized in the app. That way, if we want to renew a token or a secret for example, it is done through the Apps system.

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-webapp/pull/7850 will fix this
