### ISSUE TITLE
[BUG] call /uninstall failed: must provide Context and set the app ID: invalid input

### ISSUE THREAD

**Issue by shlasouski** [mattermost/mattermost-plugin-apps#208]
Error appears "Command failed. Error: call /uninstall failed: must provide Context and set the app ID: invalid input" during `/apps uninstall %APP_ID%` call.

**Comment by hanzei** [comment]
What is the output of `/apps info`?

**Comment by shlasouski** [comment]
Mattermost Apps plugin version: 0.7.0, 7069695, built Thu Jun 17 10:27:06 UTC 2021, Cloud Mode: false, Developer Mode: false

**Comment by hanzei** [comment]
Would you mind testing if https://github.com/mattermost/mattermost-plugin-apps/pull/207 fixes your issue?

**Comment by shlasouski** [comment]
It works. Thanks!

**Comment by hanzei** [comment]
Thanks for the feedback :+1: 

Out of curiosity: What kind of app did you build? Do you have feedback about the process to share?

**Comment by shlasouski** [comment]
Our app is Remeet.com and we have Slack bot integration for a while and now expanding it to support Mattermost. We are just starting so we’ll have more feedback over the next couple of weeks.

**This is what we have done so far:**

1. Install step: we use `/apps install http http://host.docker.internal:10010/mattermost/manifest.json?state=%ID%`. It’s important for us to retrieve GET parameters on /maifest.json route to link mattermost account where ID=(mattermost_site_url, team_id) with Remeet.com account.
2. Uninstall step: Get notification about uninstalling on Mattermost side to unlink MM account from Remeet.com.

**Q:** Is it possible to uninstall MM app via API? We would like to do it from our side when customer deactivates Remeet account. The same way is provided by Slack via revoke method (https://api.slack.com/methods/auth.revoke)

**This is what we are going to work on next:**

1. Slash commands examples:
Scheduling a new meet with /remeet from a channel or DM:
`/remeet later [topic] @user1 @user2[?] [duration]min [urgent/very urgent] [daily/weekly/bi-weekly]`

Starting a call right away with /remeet from a channel or DM:
`/remeet now [topic] [@participant1] [@participant2] [duration:optional]`

Examples:
`/remeet now Important update @emily @john`
`/remeet now Proposal review @emily @john 30min`

Adding optional participants:[@participant3]? [@participant4]?
Examples:
`/remeet now Meet with two people optional @Emily @john @erik? @amanda?`

**Q**: Is it possible to get mentioned user ids in command context?

2. Bot mention
Scheduling a new meet from a mattermost channel with @remeet bot:
`[topic] @remeet @user1 @user2[?] [duration]min [urgent/very urgent] [daily/weekly/bi-weekly] [now]`

Examples:
`Discuss plans for the next week @remeet @emily @john`
`Project standup @remeet @emily @john 5min daily`
`Production incident review @remeet @emily @john @bob? 10min urgent`

**Q:** Is it possible to get app/bot mention notification like Slack does it via https://api.slack.com/events/app_mention

3. Subscribe to events when bot is added to/left from MM channel. We will save channel on our side to be able to push messages to channels via API. For this synchronization we can use MM api to get channels where bot belongs to.
4.Subscribe to events when user is changed. We will update user info like names, email, picture.
5. Use MM as SSO provider via OAuth 2.0
6. Read user directory to invite users to Remeet.com

**Comment by hanzei** [comment]
Thanks for sharing your story and these questions!

To your questions:
1. Not yet. https://github.com/mattermost/mattermost-plugin-apps/pull/207 will add support for such endpoint for _System Admins_ to call, but no support for an app to uninstall itself.
2. Not yet. There is some initial work done https://github.com/mattermost/mattermost-plugin-apps/pull/127, but it's stale for now.
3. That is an interesting idea. I don't think there is a ticket for that. @mickmister do you know?

**Comment by mickmister** [comment]
> **Q3:** Is it possible to get app/bot mention notification like Slack does it via https://api.slack.com/events/app_mention

There is a similar [ticket](https://mattermost.atlassian.net/browse/MM-32115) to be notified when the app's bot receives a DM. It makes sense to support mentions as well :+1:

Created a ticket for the bot-mention feature here https://mattermost.atlassian.net/browse/MM-36812

@hanzei There are a few more points in @shlasouski's comment above I've copied below.

> 4. Subscribe to events when bot is added to/left from MM channel. We will save channel on our side to be able to push messages to channels via API. For this synchronization we can use MM api to get channels where bot belongs to.
> 5. Subscribe to events when user is changed. We will update user info like names, email, picture.

This makes a lot of sense. I've made a ticket for each of the items:

- Bot join/leave notifications - https://mattermost.atlassian.net/browse/MM-36813
- User profile changes notifications - https://mattermost.atlassian.net/browse/MM-36814

> 6. Use MM as SSO provider via OAuth 2.0

I believe this is implemented here:
https://docs.mattermost.com/developer/oauth-2-0-applications.html

> 7. Read user directory to invite users to Remeet.com

You can use the `/api/v4/users` endpoint to retrieve a paginated list of users:
https://api.mattermost.com/#operation/GetUsers

**Comment by mickmister** [comment]
@shlasouski I encourage you to join the [Mattermost Apps channel](https://community.mattermost.com/core/channels/mattermost-apps) on our community server. We have all of our discussion on the project there, so it would be easy to quickly iterate and discuss things about your application. Thanks so much all of your feedback!
