### ISSUE TITLE
Ensure Bot doesn't recognize existing bot if names are the same

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-apps#31]
I found this when working on the zendesk app

steps to repro:
* create integration bot through Integrations (Name the bot Zendesk)
* Install the bot through the slash command
  * `/apps install --url http://localhost:4000/mattermost/mattermost-app.json --app-secret thisisthesecret --force`

Result:
![image](https://user-images.githubusercontent.com/7575921/98400119-1a2f7d80-2029-11eb-9ef5-ecf3ea273610.png)

ensureBot in server/apps/provision.go does not find the user, but errors when trying to create the bot and returns an error to call update API, not create
https://github.com/mattermost/mattermost-plugin-apps/blob/master/server/apps/provision.go#L72

**Comment by jfrerich** [comment]
Note this is probably caused because you can create a valid username through integrations console with a capital letter

When I removed the `Zendesk` bot from the database.

Note that setting AppID in the zendesk Manifest to "Zendesk", I properly get notified that username is invalid. However, we might want to produce a better message, that tells the user no caps are allowed

![image](https://user-images.githubusercontent.com/7575921/98401016-9ececb80-202a-11eb-99a8-95bcdb0a5a9c.png)

**Comment by hanzei** [comment]
Should be fixed by https://github.com/mattermost/mattermost-plugin-apps/pull/160
