### ISSUE TITLE
Docker dev environment: Automate config settings

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-apps#329]

**Comment by mickmister** [comment]
@cwarnermm Here are the current config settings for the Apps Framework Docker development environment:

https://github.com/mattermost/mattermost-plugin-apps/blob/3e2edc619127d5beb95a98887ea7c08635bde434/dev/docker-compose.yml#L9-L26

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-apps/pull/362
