### ISSUE TITLE
Docker dev environment: Allow developer to connect App to the same docker network as the MM server

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-apps#330]
In order to have the App in development communicate to/from the other docker containers, the App's project should provide its own `docker-compose.yml` file, and have its containers configured to run in the same [Docker network](https://docs.docker.com/network) as the server, defined in the centralized `docker-compose.yml` file. This is similar to what's going on [here](https://github.com/mattermost/mattermost-plugin-apps/blob/master/dev/docker-compose.override.yml), except I think it will be easier for developer's to manage via networks, rather than overriding services in the same `docker-compose` process.

**Comment by azigler** [comment]
Based on our conversation [here](https://community-daily.mattermost.com/core/pl/kwx4hmswejbbdfhwjg7c4itfyw) I will look at doing this with the next round of app tutorial updates!

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-apps/pull/362
