### ISSUE TITLE
Web App Making Requests to Disabled "Apps" Plugin

### ISSUE THREAD

**Issue by dalenewman** [mattermost/mattermost-plugin-apps#341]
My server is 6.6.1.  I have various client versions but I've had most folks update to the latest (e.g. 5.0.4).

I have `"com.mattermost.apps" : { "Enable" : false }` in my config.json.  The apps plugin is not on the UI and not even listed in the plugins management.  But, the web app client continues to make GET requests like this: `https://my.domain.com/plugins/com.mattermost.apps/api/v1/bindings?user_id=some-user-id&channel_id=some-channel-id&team_id=some-team-id&user_agent=webapp`.  The server is returning 404 and 400 on these requests.

One of my users put together a better / chronological order of repeating events:

> I don't know if it's related, but I pulled this from the console after seeing the behavior again. This set of errors/messages seems to recur over and over in the console:

| message | reference |
| ------- | --------- |
|`computer woke up - fetching latest`| `/plugins/com.mattermost.apps/api/v1/bindings?user_id=[[UID]&channel_id=[CID]&team_id=[TID]&user_agent=webapp:1` |
| **Failed to load resource: the server responded with a status of 404 ()** | `websocket_client.tsxx:93 websocket closed <br/>websocket_client.tsxx:77` |
| `websocket re-established connection` | `/plugins/com.mattermost.apps/api/v1/bindings?user_id=[UID]&channel_id=[CID]&team_id=[TID]&user_agent=webapp:1` |
| **Failed to load resource: the server responded with a status of 404 ()** | `7onloadwff.js:71` |
| **Assertion failed: Input argument is not an HTMLInputElement** <br/> `getFormProfile @ onloadwff.js:71` | `/plugins/com.mattermost.apps/api/v1/bindings?user_id=[UID]&channel_id=[CID]&team_id=[TID]&user_agent=webapp:1` |
| **Failed to load resource: the server responded with a status of 404 ()** | `needs_team.tsxx:105` |

**Comment by mickmister** [comment]
Hi @dalenewman, thanks for reporting this issue. We apologize for any inconvenience this has brought to your server.

In the `6.6.x` release, you can disable this functionality by providing the environment variable:

```
 MM_FEATUREFLAGS_AppsEnabled=false
```

Also, the behavior you point out in the ticket is fixed in the latest release of the server `v6.7.0` in this PR: https://github.com/mattermost/mattermost-webapp/pull/8545

**Comment by dalenewman** [comment]
Thank you.  I am preparing for 6.7.0 upgrade.  Also, if the `MM_FEATUREFLAGS_AppsEnabled=false` only available as an environment variable or in the _config.json_ as well?  Thanks!

**Comment by mickmister** [comment]
> Also, is the `MM_FEATUREFLAGS_AppsEnabled=false` only available as an environment variable or in the _config.json_ as well?

@dalenewman Feature flags are specifically not config variables, and are not able to be controlled in the `config.json` file. We set the feature flags in our Cloud environment using [split.io](https://split.io), and the only other way they can be set by design is by environment variable.

**Comment by dalenewman** [comment]
Thanks so much for your help.
