### ISSUE TITLE
Is it possible update bindings by app?

### ISSUE THREAD

**Issue by PSyton** [mattermost/mattermost-plugin-apps#358]
I try to create 2 opposite bindings for /channel_header.
When we call one of it some internal state changed and we need to show another one.
When user switch channel from UI - bindings updated, because app check internal state for this channel and send right data. But I want to initiate re-request after internal state changed.
Is it possible?

**Comment by mickmister** [comment]
Hi @PSyton, there's currently no way to do this with the current feature set of the framework. To learn more about your situation, are you wanting to refresh this for just one user, or for all users at the same time?

**Comment by mickmister** [comment]
@PSyton So would the trigger be from a user action within Mattermost? A user interacts with your app in some way with in the Mattermost UI, then we want to have that specific user's client(s) refresh bindings?

**Comment by mickmister** [comment]
If this is the case, I'm thinking we can have an optional field in the call response that tells the framework to refresh each of that user's clients

**Comment by PSyton** [comment]
Yes, an optional field resolve the issue and make possible to make better UI with apps.

**Comment by PSyton** [comment]
Also, it may be not a field, but special "build-in" Call in response wirh CallResponseTypeCall.
