### ISSUE TITLE
Mattermost Apps are not getting installed.

### ISSUE THREAD

**Issue by nokhaiz-iz** [mattermost/mattermost-plugin-apps#364]
How can I install Open Source Apps in Mattermost Plugin's List.  As per your [documentation](https://developers.mattermost.com/integrate/apps/) it is using `/app` slash command but on entering this command it gives me `command not found` error.
I'll be waiting for healthy response.

**Comment by nokhaiz-iz** [comment]
So why have you enlisted Apps Documentation?

**Comment by javaguirre** [comment]
If you have access to the server or you want to use it locally, you need to install the Apps plugin, you can follow the README from the project.

https://github.com/mattermost/mattermost-plugin-apps

Once you've done that, you can start using the `/apps` command and write your own apps.

**Comment by hanzei** [comment]
Closing as stale
