### ISSUE TITLE
Inconsistency in Documentation and Example

### ISSUE THREAD

**Issue by gobsej** [mattermost/mattermost-plugin-apps#365]
I experienced  following error after installing a mattermost app on the server: `(only) one of  "submit", "form", or "bindings" must be set in a binding`

After looking at the code I found following switch case inside the function `cleanAppBinding` which specifies that one and only one the properties `submit`, `form` or `bindings` needs to be specified (this also applies for sub-bindings). According to the [example](https://developers.mattermost.com/integrate/apps/structure/bindings/#example-data-flow) and the [quick start guide](https://developers.mattermost.com/integrate/apps/quickstart/quick-start-go/#bindings-and-locations) this should not be the case.

```
hasBindings := len(b.Bindings) > 0
hasForm := b.Form != nil
hasSubmit := b.Submit != nil
switch {
	// valid cases
	case hasBindings && !hasForm && !hasSubmit:
		var newProblems error
		b.Bindings, newProblems = cleanAppBindings(app, b.Bindings, fql, userAgent, conf)
		if newProblems != nil {
			problems = multierror.Append(problems, newProblems)
		}
		if len(b.Bindings) == 0 {
			// We do not add bindings without any valid sub-bindings
			return nil, problems
		}

	case hasForm && !hasSubmit && !hasBindings:
		clean, err := cleanForm(*b.Form, conf, app.AppID)
		if err != nil {
			problems = multierror.Append(problems, err)
		}
		b.Form = &clean

	case hasSubmit && !hasBindings && !hasForm:
		// nothing to clean for submit

	default:
		problems = multierror.Append(problems, errors.Errorf(`%s: (only) one of  "submit", "form", or "bindings" must be set in a binding`, fql))
		return nil, problems
}
```

**Comment by neflyte** [comment]
FYI: The documentation around bindings is being updated in this PR: https://github.com/mattermost/mattermost-developer-documentation/pull/1111

**Comment by gobsej** [comment]
Okay great, thanks for the reply.

**Comment by luiz-filipe** [comment]
Is this really solved? Because I tried to follow the quick start guide today, and had the same problem: Using the new documentation here: http://mattermost-dev-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/1111/integrate/apps/quickstart/quick-start-go/

If I copy the `bindings.json` example file there and install my application the bindings call still fails.

**Comment by gobsej** [comment]
Oh okay sorry, maybe I closed it to fast. I closed it because it already is worked on, but I should probably wait

**Comment by neflyte** [comment]
Yes, you are correct @luiz-filipe . I am working on updating these docs now; A PR has been posted with the updates and is being reviewed: https://github.com/mattermost/mattermost-developer-documentation/pull/1111

I expect the PR to be merged in the coming weeks.

**Comment by hanzei** [comment]
Closing as https://github.com/mattermost/mattermost-developer-documentation/pull/1106 got merged
