### ISSUE TITLE
Nil pointer reference in app client

### ISSUE THREAD

**Issue by gobsej** [mattermost/mattermost-plugin-apps#366]
Hi, I believe I found a uhandled error case inside the appclient or rather experienced strange behavior which leads to a panic.

Unfortunately I am quite new to participating in open source projects and was not sure If I should have opened a pull request right away, sorry in advance.

**Comment by catalintomai** [comment]
@gobsej - opening an issue is the right first step (and then open a PR to fix the issue if so inclined). Adding as much info as possible to the issue (logs, code snippet, detailed behavior description,etc.) to help identify the fix is essential for fixing it in time. Thanks!

**Comment by gobsej** [comment]
Okay, the issue lies in the `getDirectChannelWith` function in the `mattermost_client.go:210` file.

```
func (c *Client) getDirectChannelWith(userID string) (*model.Channel, error) {
	channel, res, err := c.CreateDirectChannel(c.userID, userID)
	if res.StatusCode != http.StatusCreated && res.StatusCode != http.StatusOK {
		if err != nil {
			return nil, err
		}

		return nil, errors.Errorf("returned with status %d", res.StatusCode)
	}

	return channel, nil
}
```
The check if an error occurred is inside the check whether the statuscode of the response is a succesful one. This works if the request got an actual response but in cases where it does not (for example connection problems) the response object is `nil` and therefore panics. 

I would suggest doing the check for the error before the status check or something like that.
