### ISSUE TITLE
Changing the port doesn't affect the RootURL

### ISSUE THREAD

**Issue by javaguirre** [mattermost/mattermost-plugin-apps#391]
Not sure if intended or not, but not straight forward for someone coming from outside of the project.

![Screenshot 2022-11-18 at 12 49 46](https://user-images.githubusercontent.com/488556/202698912-f8eda0ac-9f35-4372-a6c0-f02e40591f75.png)

The manifest is in http://localhost:8888, not 8081.

I think this could be intended or not, mostly in case of being in localhost and not setting the RootURL, there are two solutions:

- We say in the documentation that if you set the port, you might need to change also the RootURL, doing nothing in the code.
- When someone changes the Port, we replace the port in the RootURL to the new port set through envvar.
- Having some kind of envvar support on the manifests, like (attachment):

![Screenshot 2022-11-18 at 12 54 16](https://user-images.githubusercontent.com/488556/202699577-d494d218-d16f-45c4-becb-a9bd8ceffa8c.png)

I understand there is a reason for this in terms of security, but I think we might need to write about it in the docs, I can do it.

**Comment by hanzei** [comment]
In https://github.com/mattermost/mattermost-plugin-apps/tree/master/test/app#test-app-for-mattermost it's stated that port should be changed by setting `PORT`. The port 8888 is not used by default.

Did you manually change the port in the manifest?

**Comment by javaguirre** [comment]
> In https://github.com/mattermost/mattermost-plugin-apps/tree/master/test/app#test-app-for-mattermost it's stated that port should be changed by setting `PORT`. Port 8888 is not used by default.
> 
> Did you manually change the port in the manifest?

I did, but that wasn't straightforward from the installation/configuration of the plugin, that's why I raise the question.

**Comment by hanzei** [comment]
The port should solely be changed via the `PORT` env variable, not by editing the code.

**Comment by javaguirre** [comment]
> The port should solely be changed via the `PORT` env variable, not by editing the code.

If we let people set the port for dev reasons, I don't see why they can't use an envvar to set the manifest url. 🤷

**Comment by javaguirre** [comment]
> > I don't see why they can't use an envvar to set the manifest url.
> 
> 
> 
> Maybe I'm missing something. The manifest URL does get updated when the env variable is set, right?

I might be missing something too, I'll write the flow I follow tomorrow and we can discuss it. thank you @hanzei !
