### ISSUE TITLE
Installing the test app fails searching the bindings

### ISSUE THREAD

**Issue by javaguirre** [mattermost/mattermost-plugin-apps#392]
I'm trying to get the test app up and running, but for some reason gives signature error in the `/app/v1/bindings` call.

![Screenshot 2022-11-18 at 13 10 11](https://user-images.githubusercontent.com/488556/202702407-245515c9-d293-4e3d-a7cc-5f347e41ac3e.png)

**Comment by javaguirre** [comment]
![Screenshot 2022-11-18 at 13 21 28](https://user-images.githubusercontent.com/488556/202703973-6f095ed5-b337-483b-9c15-678c22a0e97f.png)

It says installed, but I can't use it.

**Comment by javaguirre** [comment]
I have everything updated, using master in server, plugin-apps.

**Comment by hanzei** [comment]
Did you set `1234` as the JWT secret?

**Comment by javaguirre** [comment]
After adding the JWT in the form it works, thank you @hanzei ! 🏆
