### ISSUE TITLE
Can't see menu items when provide bindings for "/post_menu" location

### ISSUE THREAD

**Issue by PSyton** [mattermost/mattermost-plugin-apps#393]
Try to add post menu for app but can't see any new menu items on client.

When I add bindings for commands, this work as expected.

When execure `/apps debug bindings <myapp>`, I can got correct bindings.

Use server version 7.2.0 and apps plugin version 1.1.0.

**Comment by PSyton** [comment]
Sorry for the noice, I found the Item in menu, but can make only top level items. When I try to add sub-bindings no submenu appear. And when I click to top level item I'vie got system message: "This binding is not properly formed. Contact the App developer.". Submenus not supported? I can't find any docs about it, only some hints about this ability.

**Comment by hanzei** [comment]
No, submenus for post actions are not supported. They are tricky to get right on mobile and have caused CSS issues in the webapp. I don't see them being introduced in the near future.
