### ISSUE TITLE
Install command should fail is oAuth2 is disabled  

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-apps#399]
When oAuth2 is disabled - The install command for an app should fail. The user should see an ephemeral post regarding enabling oAuth2 to use Apps. (This was at one point working in an earlier release of Apps)

![image](https://user-images.githubusercontent.com/35588783/203380632-7d5c76a2-5f7d-4cd3-8948-2499b4eeff96.png)

As it stands now the Admin can attempt an install that fails
![image](https://user-images.githubusercontent.com/35588783/203380761-62782190-5c59-4656-8711-520b7244c031.png)

**Comment by hanzei** [comment]
Fixed with #316
