### ISSUE TITLE
Apps error install HTTP body "overflow"

### ISSUE THREAD

**Issue by javaguirre** [mattermost/mattermost-plugin-apps#406]
After a 502 I received the entire body of the request, I think we should truncate this.

![Screenshot 2022-12-05 at 12 26 42](https://user-images.githubusercontent.com/488556/205634693-41263581-34d8-4edc-9521-793147cb1377.png)

**Comment by KodingErrors** [comment]
how would I recreate this issue?

**Comment by javaguirre** [comment]
Not sure, I'll close it since I think it's not relevant anymore.
