### ISSUE TITLE
Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/mattermost-plugin-apps#411]
We face many entries in logs with errors:
`{"timestamp":"2022-12-06 12:58:23.703 +05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","caller":"plugin/client_rpc.go:398","plugin_id":"com.mattermost.apps","error":"timeout waiting for accept"}

{"timestamp":"2022-12-06 12:58:23.703 +05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","caller":"plugin/client_rpc.go:379","plugin_id":"com.mattermost.apps","serve_http_stream_id":396269,"error":"timeout waiting for accept"}

{"timestamp":"2022-12-06 12:58:24.899 +05:00","level":"error","msg":"Plugin failed to ServeHTTP, RPC call failed","caller":"plugin/client_rpc.go:424","plugin_id":"com.mattermost.apps","error":"EOF"}

`

after that Mattermost server freezes for some time and stop working. Over time server "alives" and back to work normally until another same errors triggers for some reasons.

Apps (com.mattermost.apps - 1.1.0)
Mattermost: 7.2

**Comment by hanzei** [comment]
Thanks for the report @KakEgorka.

Could you please set the log level in Mattermost to `DEBUG` and then post the server logs again?

**Comment by KakEgorka** [comment]
[mattermost-2022-12-06T08-00-19.813.log.gz](https://github.com/mattermost/mattermost-plugin-apps/files/10183658/mattermost-2022-12-06T08-00-19.813.log.gz)

Done

**Comment by KakEgorka** [comment]
> Thanks for the report @KakEgorka.
> 
> Could you please set the log level in Mattermost to `DEBUG` and then post the server logs again?



[mattermost-2022-12-06T08-00-19.813.log.gz](https://github.com/mattermost/mattermost-plugin-apps/files/10183667/mattermost-2022-12-06T08-00-19.813.log.gz)
Done

**Comment by hanzei** [comment]
Thank you very much :+1: @KakEgorka 

I assume the error message is thrown because the plugin crashes.

The logs start at the point where the error message already happens. Would you be open to sharing the logs since the last server start?

**Comment by KakEgorka** [comment]
> Thank you very much 👍 @KakEgorka
> 
> I assume the error message is thrown because the plugin crashes.
> 
> The logs start at the point where the error message already happens. Would you be open to sharing the logs since the last server start?

I have a log after the last server crash and restart. There, the logging level switched to an error at the end of the log
[mattermost (1).log](https://github.com/mattermost/mattermost-plugin-apps/files/10192996/mattermost.1.log)

**Comment by hanzei** [comment]
Thanks your for the timely response :+1: 

The log file does not seem to contain the server start messages. Could you please double check that these are the logs since the server start?

**Comment by KakEgorka** [comment]
> Thanks your for the timely response 👍
> 
> The log file does not seem to contain the server start messages. Could you please double check that these are the logs since the server start?

Thank you for your quick responses to messages.

Found the time to start the server. This happened after the server crashed due to a freeze.

Time start: 2022-12-06 13:01
https://drive.google.com/file/d/1iXucOqEtF6yUyEFgXL_uulX81Ef_VEkS

**Comment by hanzei** [comment]
The first apps plugin specific error message appears at `12:57:16.744`. The logs that you thankfully just send me start at `12:59:47.970`. Do you also have the logs messages before `12:57:16.744`?

**Comment by KakEgorka** [comment]
I noticed a plugin error in the logs. The plugin is disabled, but there are some actions with the plugin in the logs
`{"timestamp":"2022-12-19 12:01:03.078 +05:00","level":"debug","msg":"Access to route for non-existent plugin","caller":"app/plugin_requests.go:44","missing_plugin_id":"com.mattermost.apps","url":"/plugins/com.mattermost.apps/api/v1/bindings?user_id= xxxxxxxxxxxxxxxx&channel_id=xxxxxxxxxxxxxxxx&team_id= xxxxxxxxxxxxxxxx&user_agent=webapp","error":"plugin not found: com.mattermost.apps"}
`

**Comment by KakEgorka** [comment]
> The first apps plugin specific error message appears at `12:57:16.744`. The logs that you thankfully just send me start at `12:59:47.970`. Do you also have the logs messages before `12:57:16.744`?

[mattermost-2022-12-06T07-56-38.097.log.gz](https://github.com/mattermost/mattermost-plugin-apps/files/10256686/mattermost-2022-12-06T07-56-38.097.log.gz)
[mattermost-2022-12-06T08-00-19.813.log.gz](https://github.com/mattermost/mattermost-plugin-apps/files/10256690/mattermost-2022-12-06T08-00-19.813.log.gz)

**Comment by hanzei** [comment]
Thank for providing all of these log files. Unforettly, I can't tell the reason the plugin crashed from the logs.

But with the server restart at `2022-12-06 13:01:40.935` the plugin starts correctly. Did you encounter the `Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection` only once or does it happen regularly?

**Comment by hanzei** [comment]
Closing as the issue happened quite some time ago. @KakEgorka Please reopen, if you run into it again.
