### ISSUE TITLE
s.Configurator.GetConfig() returns nil sometimes, which causes nil pointer panic

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-apps#42]
Line 13 panics on `conf` being nil

https://github.com/mattermost/mattermost-plugin-apps/blob/766933b1c93abf887476db81faaccaf9bd7cf7f5/server/apps/apps.go#L10-L14

I don't know what causes the issue. Restarting the plugin fixes it, then it doesn't seem to happen again. I reproduced this specifically with a fresh database this time.

**Comment by hanzei** [comment]
Fixed with [`61c304e` (#96)](https://github.com/mattermost/mattermost-plugin-apps/pull/96/commits/61c304e2fea36d31e463c0ffa7f6ad1ff6724c45)
