### ISSUE TITLE
Marketplace install button does not seem to fire correct install command

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-apps#420]
Marketplace installation seems broken. 

**note**: there may be. more going on here as the app uysed to test is not showing on all servers asI would expect.

Testing suggests this is a change in the Apps plugin and not the webapp. Uploading current `master` onto a server with an older build where the install worked seems to introduce this issue.

![image](https://user-images.githubusercontent.com/35588783/209009932-26dadb7e-4557-47ed-8402-b333d59e3989.png)

Steps:
- Pull latest `master`
- Add `"drive": "v1.0.0"` to the manifest and build
- Upload to any `.test.mattermost.cloud` server
- Note Drive now shows in the market place
- Click install

**Observed**: Parsing error
Not that installing via slash command works as expected still

**Comment by hanzei** [comment]
@DHaussermann Could you please share the output of `/apps info`?

**Comment by DHaussermann** [comment]
@hanzei see info
![image](https://user-images.githubusercontent.com/35588783/210393759-a21151f0-ca2d-4081-94e7-17d7ba846e48.png)

The commit link is pointing here: https://github.com/mattermost/mattermost-plugin-apps/commit/1b35ad55fb48d0650a1f4a8d022f4400d51dbcb3

**Comment by hanzei** [comment]
Will be fixed via https://mattermost.atlassian.net/browse/MM-50111
