### ISSUE TITLE
New logging feature is not working for me

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-apps#422]
I can't make the logging post to a channel. 

Steps:
- Get latests `master` and build
- Upload latest Apps Plugin to a test server
- Start the test-app
- Install test app on the sere via http 
- Create a channel called `apps-logs`
- Post `/apps debug logs --level debug --channel ~apps-logs`
- Enable other apps and switch channels a few times to genearate logs
- Check server logs to ensure there are logs such as 
```
{"timestamp":"2022-12-21 21:39:11.548 Z","level":"debug","msg":"failed to fetch app bindings","caller":"app/plugin_api.go:970","plugin_id":"com.mattermost.apps","path":"/api/v1/bindings","request_id":"diuzxuypd7dd8rcr673q71h9cw","from_user_id":"i77ghs7jypb7bgwuhg8uox5ana","error":"1 error occurred:\n\t* received app error: upstream call failed: function failed with status code 0, body \n\n","plugin_caller":"server/proxy/bindings.go:67"}
{"timestamp":"2022-12-21 21:39:11.551 Z","level":"debug","msg":"Handled HTTP request","caller":"app/plugin_api.go:970","plugin_id":"com.mattermost.apps","request_id":"diuzxuypd7dd8rcr673q71h9cw","plugin_caller":"server/httpin/service.go:166","from_user_id":"i77ghs7jypb7bgwuhg8uox5ana","path":"/api/v1/bindings"}
{"timestamp":"2022-12-21 21:39:14.034 Z","level":"debug","msg":"Handled HTTP request","caller":"app/plugin_api.go:970","plugin_id":"com.mattermost.apps","request_id":"b9fq4tar6jrfiphdzu8haaef6w","plugin_caller":"server/httpin/service.go:166","from_user_id":"i77ghs7jypb7bgwuhg8uox5ana","path":"/api/v1/call"}
```
- Return to the target channel

**Observed**: Nothing has been posted

**Comment by levb** [comment]
@DHaussermann you have the dev mode on on the server?

**Comment by DHaussermann** [comment]
Thanks @levb dev mode **was** enabled however this is wired a bit odd. It had not been properly enabled as `Enable Testing Commands` not been properly enabled as well
![image](https://user-images.githubusercontent.com/35588783/209157543-b4abc659-bd2b-41df-8ab8-bce3e77e000c.png)

This could be considered user error I suppose.

After some exploratory testing this functions exactly as expected once the test commands are enabled. 

As I recall - `Enable Testing Commands` needing to be enabled was an existing issue fir debug functionality in the past. 

I feel this should be closed as the sysadmin can make the logging work. I can open a  new issue about the flags and we can discuss if it's needed in `v1.2.1`
