### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by wetneb** [mattermost/mattermost-plugin-apps#494]
In the README.md of this repository, the documentation link points to:
https://developers.mattermost.com/integrate/apps/
Which is a 404 on my end.

This link can also be found in the plugin's manifest, and hence on https://mattermost.com/marketplace/app-framework/
as well as on https://github.com/mattermost/mattermost-mobile/issues/3883.

**Comment by lieut-data** [comment]
Thanks, @wetneb! This repository is now deprecated, but I failed to make that clear. I've linked a PR to address both this, and link to the now legacy documentation you raised.

@cwarnermm, can you help retire https://mattermost.com/marketplace/app-framework/?

**Comment by cwarnermm** [comment]
Thanks, @wetneb and @lieut-data, for raising this. I'll retire the Marketplace listing. Thanks, @lieut-data, for the README update!

**Comment by wetneb** [comment]
Nevermind, I found the answer to my question in https://forum.mattermost.com/t/transition-from-apps-framework-to-plugin-framework-in-mattermost-v10/19330
